language: python
#
# Decrypt secret file and install dependences
#
before_install:
- openssl aes-256-cbc -K $encrypted_7000bf93944d_key -iv $encrypted_7000bf93944d_iv
  -in secret.json.enc -out secret.json -d
#
# Python version and requirements
#
python:
  - 2.7
#
#
# Skips installation step
#
install:
  - pip install -t lib flask
  - git add -f lib/*
  - git commit -m "Add Dependences"
#
# Unit tests
#
script: true
#
# Deploy to Google App Engine
#
deploy:
  provider: gae
  keyfile: secret.json
  project: recommendation-system-160616
  # Make deploy without version
  default: true
  # Make deploy with master branch only
  on: master
