language: python

dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_7000bf93944d_key -iv $encrypted_7000bf93944d_iv
  -in secret.json.enc -out secret.json -d

python:
- 2.7

install:
  - pip install -t lib -r pip_requirements
  - envsubst < app.yaml > temp.yaml
  - mv temp.yaml app.yaml
  
script:
  - FILE_TO_FIX=lib/spotipy/oauth2.py
  - sed -i "s/if response.status_code is not 200:/if response.status_code != 200:/" $FILE_TO_FIX
  - python -m py_compile $FILE_TO_FIX

deploy:
  provider: gae
  keyfile: secret.json
  project: recommendation-system-160616
  version: 2
  on: master
  skip_cleanup: true

notifications:
  email: false

